name = "FEMFractionalQuadrature"
uuid = "224d28b5-65d5-4fc1-b150-12919de04b0c"
authors = [
    "David Gomez-Castro <david@gomezcastro.xyz>",
    "Stefano Fronzoni <fronzoni@maths.ox.ac.uk>"]
version = "1.0.0"

[deps]
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"

[compat]
HypergeometricFunctions = "0.3.28"
JLD2 = "0.6.2"
JuliaFormatter = "2.1.0"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
Plots = "1.40.11"
SparseArrays = "1.11.0"
SpecialFunctions = "2.5.1"
ToeplitzMatrices = "0.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]