name = "FEMFractionalQuadrature"
uuid = "224d28b5-65d5-4fc1-b150-12919de04b0c"
version = "1.0.0"
authors = ["David Gomez-Castro <david@gomezcastro.xyz>", "Stefano Fronzoni <fronzoni@maths.ox.ac.uk>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Epsteinlib_jll = "4ec54591-1743-56ec-8704-f258a6d96b61"
ExtendableFEM = "a722555e-65e0-4074-a036-ca7ce79a4aed"
ExtendableFEMBase = "12fb9182-3d4c-4424-8fd1-727a0899810c"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[compat]
Epsteinlib_jll = "0.5.0"
StaticArrays = "1.9.15"
julia = "1.12.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
